CREATE TABLE customer_subscription_plans (id TEXT PRIMARY KEY, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT, price NUMERIC NOT NULL, billing_period TEXT NOT NULL, duration_days INTEGER NOT NULL, is_active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE customer_subscriptions (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL, plan_id TEXT NOT NULL REFERENCES customer_subscription_plans(id), status TEXT NOT NULL CHECK(status IN ('PENDING','ACTIVE','EXPIRED','CANCELLED','SUSPENDED','REFUNDED')), payment_status TEXT NOT NULL CHECK(payment_status IN ('PENDING','PAID','FAILED','REFUNDED','PARTIALLY_REFUNDED')), start_date TEXT NOT NULL, expiry_date TEXT NOT NULL, auto_renew INTEGER NOT NULL DEFAULT 0, cancelled_at TEXT, cancellation_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE customer_subscription_payments (id TEXT PRIMARY KEY, customer_subscription_id TEXT NOT NULL REFERENCES customer_subscriptions(id), customer_id TEXT NOT NULL, amount NUMERIC NOT NULL, currency TEXT NOT NULL, payment_gateway TEXT NOT NULL, gateway_transaction_id TEXT UNIQUE NOT NULL, payment_status TEXT NOT NULL, paid_at TEXT, refunded_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE customer_enquiries (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL, listing_type TEXT NOT NULL CHECK(listing_type IN ('warehouse','logistics')), warehouse_id TEXT, logistics_listing_id TEXT, provider_user_id TEXT NOT NULL, provider_name TEXT, listing_name TEXT NOT NULL, subject TEXT NOT NULL, message TEXT NOT NULL, preferred_contact_method TEXT NOT NULL, preferred_callback_time TEXT, booking_reference TEXT, status TEXT NOT NULL CHECK(status IN ('DRAFT','SENT','VIEWED','RESPONDED','CLOSED','CANCELLED')), viewed_at TEXT, responded_at TEXT, closed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE enquiry_messages (id TEXT PRIMARY KEY, enquiry_id TEXT NOT NULL REFERENCES customer_enquiries(id), sender_id TEXT NOT NULL, sender_role TEXT NOT NULL, message TEXT NOT NULL, is_read INTEGER NOT NULL DEFAULT 0, read_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE contact_access_logs (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL, subscription_id TEXT, listing_type TEXT NOT NULL, listing_id TEXT NOT NULL, action_type TEXT NOT NULL, access_granted INTEGER NOT NULL, denial_reason TEXT, ip_address TEXT, user_agent TEXT, created_at TEXT NOT NULL);
CREATE INDEX customer_subscriptions_customer_idx ON customer_subscriptions(customer_id, status, expiry_date);
CREATE INDEX customer_enquiries_customer_idx ON customer_enquiries(customer_id, created_at);
CREATE INDEX customer_enquiries_provider_idx ON customer_enquiries(provider_user_id, created_at);
