import {read,write} from './storage';
import {appendOwnedRecord,normalizeUser,readOwnedCollection,scopedKey} from './accessControl';
export const VEHICLE_KEYS={draft:'vehicle_showcase_draft',vehicles:'vehicle_showcase_listings',requests:'vehicle_verification_requests',ownerNotifications:'logistics_owner_notifications',systemNotifications:'system_owner_notifications'};
export const loadVehicleDraft=user=>read(scopedKey(VEHICLE_KEYS.draft,user),null);
export const saveVehicleDraft=(value,user)=>{const saved={...value,lastSavedAt:new Date().toISOString()};write(scopedKey(VEHICLE_KEYS.draft,user),saved);return saved};
export const clearVehicleDraft=user=>localStorage.removeItem(`trustlogix:${scopedKey(VEHICLE_KEYS.draft,user)}`);
export const getOwnerVehicles=user=>readOwnedCollection(VEHICLE_KEYS.vehicles,user);
export const maskRegistration=value=>{const clean=(value||'').replace(/\s/g,'').toUpperCase();return clean.length>4?`${clean.slice(0,-4).replace(/([A-Z]{2})(\d{1,2})([A-Z]{1,3})/,'$1 $2 $3')} ****`:'Private'};
export function submitVehicle(data,user){const owner=normalizeUser(user||read('user',null)),now=new Date().toISOString();const vehicle=appendOwnedRecord(VEHICLE_KEYS.vehicles,{...data,id:`VEH-${Date.now()}`,status:'Verification Pending',listingStatus:'Unpublished',publicVisible:false,submittedAt:now},owner);appendOwnedRecord(VEHICLE_KEYS.requests,{id:`VVR-${Date.now()}`,vehicleId:vehicle.id,registration:data.basic.registration,category:data.basic.category,manufacturer:data.basic.manufacturer,model:data.basic.model,owner:owner.name,company:data.basic.company||owner.name,payload:`${data.capacity.payload} ${data.capacity.payloadUnit}`,goods:data.services.goods,areas:data.areas.deliveryCities,status:'Verification Pending',submittedAt:now},owner);appendOwnedRecord(VEHICLE_KEYS.ownerNotifications,{id:Date.now(),message:'Vehicle submitted for TrustLogix verification.',createdAt:now,read:false},owner);write(VEHICLE_KEYS.systemNotifications,[{id:Date.now()+1,ownerId:owner.id,businessId:owner.businessId,message:`New vehicle verification request: ${data.basic.category} ${data.basic.model}`,createdAt:now,read:false},...read(VEHICLE_KEYS.systemNotifications,[])]);clearVehicleDraft(owner);return vehicle}
