export const emailOk=v=>/^\S+@\S+\.\S+$/.test(v||'');
export const phoneOk=v=>(v||'').replace(/\D/g,'').replace(/^91(?=\d{10}$)/,'').length===10;
export const pinOk=v=>/^[1-9]\d{5}$/.test(v||'');
const positive=v=>Number(v)>0;
export function validateStep(step,d){const e={};const req=(obj,keys)=>keys.forEach(k=>{if(!String(obj[k]??'').trim())e[k]='This field is required.';});
 if(step===0){req(d.basic,['name','category','company','shortDescription','description','year','contactName','designation']);if(d.basic.name&&d.basic.name.length<3)e.name='Use at least 3 characters.';if(d.basic.shortDescription&&d.basic.shortDescription.length<40)e.shortDescription='Use at least 40 characters.';if(d.basic.description&&d.basic.description.length<150)e.description='Use at least 150 characters.';if(d.basic.year&&(Number(d.basic.year)<1900||Number(d.basic.year)>new Date().getFullYear()))e.year='Enter a valid year.';if(d.basic.category==='Other'&&!d.basic.customCategory)e.customCategory='Enter the custom category.';}
 if(step===1){req(d.location,['country','state','city','area','address','landmark','pin']);if(d.location.pin&&!pinOk(d.location.pin))e.pin='Enter a valid 6-digit Indian PIN code.';if(d.location.latitude&&(Number(d.location.latitude)<-90||Number(d.location.latitude)>90))e.latitude='Latitude must be between -90 and 90.';if(d.location.longitude&&(Number(d.location.longitude)<-180||Number(d.location.longitude)>180))e.longitude='Longitude must be between -180 and 180.';}
 if(step===2){req(d.capacity,['totalArea','availableArea','areaUnit','maxCapacity','capacityUnit','minimumSpace']);['totalArea','availableArea','maxCapacity','minimumSpace'].forEach(k=>{if(d.capacity[k]&&!positive(d.capacity[k]))e[k]='Enter a positive value.'});if(Number(d.capacity.availableArea)>Number(d.capacity.totalArea))e.availableArea='Available area cannot exceed total area.';if(Number(d.capacity.minimumSpace)>Number(d.capacity.availableArea))e.minimumSpace='Minimum space cannot exceed available area.';if(d.capacity.availablePallets&&Number(d.capacity.availablePallets)>Number(d.capacity.totalPallets))e.availablePallets='Cannot exceed total pallets.';}
 if(step===3){if(!d.storage.types.length)e.storageTypes='Select at least one storage type.';if(!d.storage.goods.length)e.goods='Select at least one accepted goods type.';if(d.storage.types.includes('Custom Storage')&&!d.storage.customType)e.customType='Describe the custom storage.';}
 if(step===4&&!d.facilities.selected.length)e.facilities='Select at least one facility.';
 if(step===5){req(d.pricing,['startingPrice','pricingUnit','minimumDuration','durationUnit','availabilityStatus','openingTime','closingTime']);if(d.pricing.startingPrice&&!positive(d.pricing.startingPrice))e.startingPrice='Enter a valid price.';}
 if(step===6){if(d.media.images.length<5)e.images='Upload at least five genuine warehouse images.';}
 if(step===7){req(d.contact,['primaryPhone','name','designation','email','hoursFrom','hoursTo','preferredMethod']);if(d.contact.primaryPhone&&!phoneOk(d.contact.primaryPhone))e.primaryPhone='Enter a valid 10-digit mobile number.';if(d.contact.email&&!emailOk(d.contact.email))e.email='Enter a valid email.';if(d.contact.alternatePhone&&d.contact.alternatePhone.replace(/\D/g,'')===d.contact.primaryPhone.replace(/\D/g,''))e.alternatePhone='Alternate number must differ from primary.';}
 if(step===8){const types=d.documents.map(x=>x.type);['Business Registration Proof','Owner Identity Proof','Warehouse Address Proof'].forEach(x=>{if(!types.includes(x))e.documents=`Upload required documents, including ${x}.`});if(d.storage.types.some(x=>x.includes('Cold'))&&!types.includes('Cold-Storage Licence'))e.documents='Cold storage requires a Cold-Storage Licence.';if(d.storage.hazardous&&!types.includes('Hazardous Goods Certificate'))e.documents='Hazardous goods require certification.';}
 if(step===9&&d.declarations.some(x=>!x))e.declarations='Accept every declaration before submitting.';return e;}
export const validateAll=d=>Array.from({length:10},(_,i)=>validateStep(i,d));
