import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { Toaster } from 'react-hot-toast';
import { AuthProvider } from './context/AuthContext';
import App from './App';
import './styles/variables.css';
import './styles/globals.css';
import './styles/responsive.css';
import './styles/roles.css';
import './styles/landing.css';
import './styles/classification-rating.css';
import './styles/auth-theme.css';
import './styles/guest-access.css';
import './styles/customer-sidebar-filter-sizing.css';
import './styles/brand.css';
import './styles/public-marketplace-filters.css';
import './styles/account-menu.css';
import './styles/independent-scroll.css';
import './styles/customer-compare.css';
import './styles/landing-animation-suite.css';
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><AuthProvider><App /><Toaster position="top-right" /></AuthProvider></BrowserRouter></React.StrictMode>);
